apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: title-middle-v1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: title-middle
        version: 0.1.0
    spec:
      containers:
      - name: title-middle
        image: title-middle:0.1.0
        ports:
        - containerPort: 8080
        imagePullPolicy: IfNotPresent #For local dev, use local docker repo
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 5
