apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: title-edge
  labels:
    app: title-edge
spec:
  replicas: 1
  selector:
    matchLabels:
      app: title-edge
  template:
    metadata:
      labels:
        app: title-edge
    spec:
      containers:
      - name: title-edge
        image: title-edge:0.1.0
        ports:
        - containerPort: 8080
        imagePullPolicy: IfNotPresent #For local dev, use local docker repo
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 5
