apiVersion: v1
kind: Service
metadata:
  name: title-edge
  labels:
    app: title-edge
    #role: ??
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    name: http
  selector:
    app: title-edge
    #role: ??
