apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: search-edge
  labels:
    app: search-edge
    version: 0.1.0
spec:
  replicas: 1
  selector:
    matchLabels:
      app: search-edge
  template:
    metadata:
      labels:
        app: search-edge
    spec:
      containers:
      - name: search-edge
        image: search-edge:0.1.0
        ports:
        - containerPort: 8080
        imagePullPolicy: IfNotPresent #For local dev, use local docker repo
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8081
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8081
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 5
