apiVersion: v1
kind: Service
metadata:
  name: search-edge
  labels:
    app: search-edge
    #role: ??
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    name: http
  selector:
    app: search-edge
    #role: ??
