apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: title-middle-route
spec:
  destination:
    name: title-middle
    namespace: rma
  precedence: 1
  route:
  - labels:
      version: 0.1.0
    weight: 50
  - labels:
      version: 0.2.0
    weight: 50
