apiVersion: config.istio.io/v1alpha2
kind: DestinationPolicy
metadata:
  name: title-middle-v2-cb
spec:
  destination:
    name: title-middle
    namespace: rma
    labels:
      version: 0.2.0
  circuitBreaker:
    simpleCb:
      maxConnections: 1
      httpMaxPendingRequests: 1
      sleepWindow: 5m
      httpDetectionInterval: 30s
      httpMaxEjectionPercent: 100
      httpConsecutiveErrors: 5
      httpMaxRequestsPerConnection: 1
