apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: title-middle-90-10
spec:
  destination:
    name: title-middle
  precedence: 4
  route:
  - labels:
      version: v1
    weight: 90
  - labels:
      version: v2
    weight: 10
